module.exports = {
  apps: [
    {
      name: 'worker',
      script: './worker.js',
      instances: 2,
      autorestart: true,
      watch: "worker.js",
      max_memory_restart: '1G',
      kill_timeout: 30000,
      exec_mode: "cluster",
    },
    {
      name: 'controller',
      script: './controller.js',
      autorestart: true,
      watch: "controller.js",
      max_memory_restart: '1G',
      kill_timeout: 10000,
      exec_mode: "cluster",
    },
    {
      name: 'localstore',
      script: './localstore.js',
      autorestart: true,
      watch: "localstore.js",
      max_memory_restart: '1G',
      kill_timeout: 10000,
      exec_mode: "cluster",
    },
    {
      name: 'remotestore',
      script: './remotestore.js',
      autorestart: true,
      watch: "remotestore.js",
      max_memory_restart: '1G',
      kill_timeout: 10000,
      exec_mode: "cluster",
    },
    {
      name: "nats-local",
      script: "./gnatsd",
      args: "-p 4222 -cluster nats://localhost:4248 -m 8222",
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    {
      name: "nats-remote",
      script: "./gnatsd",
      args: "-p 5222 -cluster nats://localhost:5248 -m 9222",
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    {
      name: "nats-local-board",
      script: "././node_modules/.bin/natsboard",
      args: "--nats-mon-url http://localhost:8222 --port 3000",
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    {
      name: "nats-remote-board",
      script: "././node_modules/.bin/natsboard",
      args: "--nats-mon-url http://localhost:9222 --port 3001",
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
  ],
};
